name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: docker container
        uses: docker://centos:7
      - uses: actions/checkout@v1
      - name: test
        run: ls
