name: Docker test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: docker container
        uses: docker://centos:7
      - uses: actions/checkout@master
      - name: test
        run: |
          docker run -itd --name example centos:7
          docker exec -it example yum -y install httpd
          docker exec -it example rpm -qa
