name: Docker test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: docker container
        uses: docker://centos:7
        with:
          run: |
            yum -y install httpd
      # - uses: actions/checkout@master
      - name: test
        run: |
          docker ps -a
          docker images
