name: ansible test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - name: ansible playbook test
        run: |
          pip install ansible
          ansible-playbok main.yml
